version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nesttest
    environment:
      - HOST=db
      - PORT=${PORT}
      - USER=postgres
      - PASSWORD=postgres
      - DATABASE=postgres
      - JWT=secret
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
